In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import requests
import os
import tqdm

In [2]:
file_path = "/media/lars/F77E-7D07/"

In [3]:
locations_with_images = pd.read_csv(file_path + "locations_with_images.csv")

In [4]:
locations_with_images

,Unnamed: 0,title,app_id,x,y,image_path,w,h
0,0,Prince of Persia: Warrior Within™,13500,-27.830263,-50.389065,thumbnails/13500.jpg,267,400
1,1,Monaco: What's Yours Is Mine,113020,-23.661060,-32.131130,thumbnails/113020.jpg,267,400
2,2,Escape Dead Island,226560,-21.555323,-15.315650,thumbnails/226560.jpg,267,400
3,3,METAL SLUG 3,250180,-21.135366,-32.897854,thumbnails/250180.jpg,267,400
4,4,Enclave,253980,-25.930891,-7.152575,thumbnails/253980.jpg,267,400
...,...,...,...,...,...,...,...,...
2527,2663,Toodee and Topdee,1303950,8.808064,-12.508147,thumbnails/1303950.jpg,267,400
2528,2664,Strategic Mind: Blitzkrieg,1200330,29.427100,51.273785,thumbnails/1200330.jpg,400,400
2529,2665,Burnhouse Lane,1846460,-14.998375,-3.092490,thumbnails/1846460.jpg,267,400
2530,2666,RiffTrax: The Game,1707870,6.705591,31.316670,thumbnails/1707870.jpg,267,400
2531,2667,MotoGP™22,1710580,-31.837030,-18.578090,thumbnails/1710580.jpg,267,400

In [5]:
locations_with_images = locations_with_images.drop(["Unnamed: 0", "app_id"], axis=1)

In [6]:
locations_with_images

,title,x,y,image_path,w,h
0,Prince of Persia: Warrior Within™,-27.830263,-50.389065,thumbnails/13500.jpg,267,400
1,Monaco: What's Yours Is Mine,-23.661060,-32.131130,thumbnails/113020.jpg,267,400
2,Escape Dead Island,-21.555323,-15.315650,thumbnails/226560.jpg,267,400
3,METAL SLUG 3,-21.135366,-32.897854,thumbnails/250180.jpg,267,400
4,Enclave,-25.930891,-7.152575,thumbnails/253980.jpg,267,400
...,...,...,...,...,...,...
2527,Toodee and Topdee,8.808064,-12.508147,thumbnails/1303950.jpg,267,400
2528,Strategic Mind: Blitzkrieg,29.427100,51.273785,thumbnails/1200330.jpg,400,400
2529,Burnhouse Lane,-14.998375,-3.092490,thumbnails/1846460.jpg,267,400
2530,RiffTrax: The Game,6.705591,31.316670,thumbnails/1707870.jpg,267,400
2531,MotoGP™22,-31.837030,-18.578090,thumbnails/1710580.jpg,267,400

In [7]:
import pandas as pd

# Export to JSON
locations_with_images.to_json("locations.json", orient="records")